name: Build Android with EAS

on:
  workflow_dispatch:
    inputs:
      build_profile:
        description: "EAS build profile"
        required: true
        default: "production"
        type: choice
        options:
          - development
          - preview
          - production

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Validate eas.json
        run: |
          if ! jq empty eas.json; then
            echo "eas.json is not valid JSON"
            exit 1
          fi

      - name: Install dependencies
        run: |
          echo "Run npm install"
          npm install
          echo "Run npm install -g eas-cli sharp-cli typescript"
          npm install -g eas-cli sharp-cli typescript
          echo 'Run echo "$(npm bin -g)" >> $GITHUB_PATH'
          echo "$(npm bin -g)" >> $GITHUB_PATH

      - name: Update Expo packages
        run: |
          npx expo install --fix

      - name: Verify EAS CLI installation
        run: eas --version

      - name: Get name from package.json
        id: get_name
        run: |
          NAME=$(jq -r '.name' package.json)
          echo "NAME=$NAME" >> $GITHUB_ENV

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build APK
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          NODE_OPTIONS: --no-warnings
          EAS_BUILD_PROFILE: ${{ github.event.inputs.build_profile }}
          NAME: ${{ env.NAME }}
          VERSION: ${{ env.VERSION }}
          FILENAME: "${{ env.NAME }}-v${{ env.VERSION }}-${{ github.event.inputs.build_profile }}.apk"
        run: |
          set -e
          echo "Starting build process with npx eas build --profile $EAS_BUILD_PROFILE --platform android --local --non-interactive --output $FILENAME"
          npx eas build --profile $EAS_BUILD_PROFILE --platform android --local --non-interactive --output $FILENAME
          echo "Build process completed."
          echo "APK_PATH=$FILENAME" >> $GITHUB_ENV

      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.APK_PATH }}
          path: ${{ env.APK_PATH }}
          if-no-files-found: error
          retention-days: 90

      - name: Upload build logs on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: build-logs
          path: build-output.log
