name: Build Expo APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install dependencies
      run: |
        npm install
        npm install -g eas-cli
        echo "$(npm bin -g)" >> $GITHUB_PATH

    - name: Verify EAS CLI installation
      run: eas --version

    - name: Generate APK filename
      run: node generate-filename.js
      env:
        EAS_BUILD_PROFILE: production

    - name: Build APK
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      run: |
        OUTPUT=$(npx eas build --profile production --platform android --local --non-interactive --output build-output.apk)
        echo "$OUTPUT"
        APK_PATH=$(echo "$OUTPUT" | grep -oP '(?<=You can find the build artifacts in )[^ ]+')
        echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV

    - name: Rename APK file
      run: |
        FILENAME=$(cat apk-filename.txt)
        mv "$APK_PATH" "$FILENAME"
        echo "RENAMED_APK=$FILENAME" >> $GITHUB_ENV

    - name: Upload APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: ${{ env.RENAMED_APK }}
