name: Build Expo APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # Set an overall job timeout

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Validate eas.json
      run: |
        if ! jq empty eas.json; then
          echo "eas.json is not valid JSON"
          exit 1
        fi

    - name: Install dependencies
      run: |
        npm install
        npm install -g eas-cli sharp-cli
        echo "$(npm bin -g)" >> $GITHUB_PATH

    - name: Update Expo packages
      run: |
        npx expo install --fix
        npm install react-native@0.72.10

    - name: Verify EAS CLI installation
      run: eas --version

    - name: Generate APK filename
      run: node generate-filename.js
      env:
        EAS_BUILD_PROFILE: production

    - name: Build APK
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        NODE_OPTIONS: --no-warnings
      run: |
        set -e
        echo "Starting build process..."
        npx eas-cli build --profile production --platform android --local --non-interactive --output app-release.apk
        echo "Build process completed."
        echo "APK_PATH=app-release.apk" >> $GITHUB_ENV

    - name: Rename APK file
      if: success()
      run: |
        FILENAME=$(cat apk-filename.txt)
        mv "$APK_PATH" "$FILENAME"
        echo "RENAMED_APK=$FILENAME" >> $GITHUB_ENV

    - name: Upload APK artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: ${{ env.RENAMED_APK }}

    - name: Upload build logs on failure
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: build-logs
        path: build-output.log
